name: QADemo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.21.5
  - pip=21.3.1
  - python=3.8.13
  - pytorch=1.11.0
  - pip:
      - streamlit==1.13.0
      - streamlit-aggrid==0.3.3
      - mypy==0.812
      - nltk>=3.3
      - pytest==6.2.5
      - tokenizers==0.12.1
      - transformers==4.19.4