name: QADemo
channels:
  - pytorch-nightly
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy-base=1.23.1
  - pip=22.2.2
  - python=3.9.13
  - pytorch=1.13.0
  - pytorch-mutex=1.0
  - six=1.16.0
  - sqlite=3.39.3
  - typing_extensions=4.3.0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - allennlp==2.10.0
    - altair==4.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - base58==2.1.1
    - bcrypt==4.0.0
    - blinker==1.5
    - blis==0.7.8
    - boto3==1.24.86
    - botocore==1.27.86
    - cached-path==1.1.6
    - cachetools==5.2.0
    - catalogue==2.0.8
    - charset-normalizer==2.1.1
    - click==8.0.4
    - commonmark==0.9.1
    - cymem==2.0.6
    - datasets==2.4.0
    - decorator==5.1.1
    - deepdiff==5.8.1
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - evaluate==0.2.2
    - extra-streamlit-components==0.1.56
    - fairscale==0.4.6
    - filelock==3.7.1
    - fire==0.4.0
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-api-core==2.8.2
    - google-auth==2.12.0
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.5.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.4.0
    - googleapis-common-protos==1.56.4
    - h5py==3.7.0
    - huggingface-hub==0.10.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - iniconfig==1.1.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonnet==0.18.0
    - jsonschema==4.16.0
    - jury==2.2.2
    - langcodes==3.3.0
    - lmdb==1.3.0
    - markupsafe==2.1.1
    - more-itertools==8.14.0
    - multidict==6.0.2
    - multiprocess==0.70.13
    - murmurhash==1.0.8
    - nltk==3.7
    - numpy==1.23.3
    - ordered-set==4.1.0
    - packaging==21.3
    - pandas==1.5.0
    - pathtools==0.1.2
    - pathy==0.6.2
    - pillow==9.2.0
    - pluggy==1.0.0
    - preshed==3.0.7
    - promise==2.3
    - protobuf==3.20.0
    - psutil==5.9.2
    - py==1.11.0
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.8.2
    - pydeck==0.8.0b3
    - pygments==2.13.0
    - pyjwt==2.5.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytest==7.1.3
    - python-dateutil==2.8.2
    - python-decouple==3.6
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - regex==2022.9.13
    - responses==0.18.0
    - rich==12.1.0
    - rouge-score==0.0.4
    - rsa==4.9
    - s3transfer==0.6.0
    - sacremoses==0.0.53
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - semver==2.13.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.9.10
    - seqeval==1.2.2
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - sklearn==0.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - spacy==3.3.1
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.4
    - streamlit==1.13.0
    - streamlit-aggrid==0.3.3
    - streamlit-modal==0.0.5
    - tensorboardx==2.1
    - termcolor==1.1.0
    - thinc==8.0.17
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.12.1
    - torchvision==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.4.0
    - transformers==4.20.1
    - trapper==0.0.10
    - typer==0.4.2
    - tzdata==2022.4
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - wandb==0.12.21
    - wasabi==0.10.1
    - watchdog==2.1.9
    - xxhash==3.0.0
    - yarl==1.8.1
    - zipp==3.8.1